# Generated by Django 3.1.6 on 2021-02-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('Date_started', models.DateField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fly_minute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_meeting', models.CharField(choices=[('Email', 'Email'), ('Zoom', 'Zoom'), ('Alternative', 'Alternative')], max_length=100)),
                ('date', models.DateField()),
                ('Time', models.TimeField()),
                ('minute_prepared_by', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('authorize_by', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('phone', models.IntegerField()),
                ('item', models.TextField()),
                ('owner', models.CharField(max_length=25)),
                ('recommendations', models.TextField()),
                ('notes', models.TextField()),
                ('issues', models.TextField()),
                ('resolutions', models.TextField()),
                ('resolution_Owner', models.CharField(max_length=25)),
                ('due_date', models.DateField()),
                ('Action', models.TextField()),
                ('department_or_person_responsible', models.CharField(max_length=25)),
                ('authorize_by_chairman', models.CharField(choices=[('Andrew Kausiama', 'Andrew Kausiama'), ('Simeon Athy', 'Simeon Athy'), ('Votasui Maclemzie Reur', 'Votasui Maclemzie Reur'), ('Serah Obed', 'Serah Obed'), ('Steven Tahi', 'Steven Tahi')], max_length=100)),
                ('authorize_by_director_ex_officio', models.CharField(choices=[('Andrew Kausiama', 'Andrew Kausiama'), ('Simeon Athy', 'Simeon Athy'), ('Votasui Maclemzie Reur', 'Votasui Maclemzie Reur'), ('Serah Obed', 'Serah Obed'), ('Steven Tahi', 'Steven Tahi')], max_length=100)),
                ('authorize_by_directors', models.TextField(choices=[('Andrew Kausiama', 'Andrew Kausiama'), ('Simeon Athy', 'Simeon Athy'), ('Votasui Maclemzie Reur', 'Votasui Maclemzie Reur'), ('Serah Obed', 'Serah Obed'), ('Steven Tahi', 'Steven Tahi')], max_length=100)),
                ('Minute_approved_by_the_Chairmen', models.CharField(max_length=25)),
                ('Approval_date', models.DateField()),
            ],
        ),
    ]
