# Generated by Django 3.1.6 on 2021-02-18 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minute', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmembers',
            old_name='Date_started',
            new_name='start_date',
        ),
    ]
